### ISSUE TITLE
Feature Request: Country Names, City Names, & Preferred Language

### ISSUE THREAD

**Issue by timtamothee** [helium/mappers#84]
I have a feature request. When zoomed out on Mappers or when looking at another country, it can be difficult to pinpoint the precise location of a city or boundary of a country.

Possible features:

1. Country Names: 
- Country names when zoomed out in full view.

2. City Names: 
- City names in a more zoomed-out view.

3. Zoomed Out Coverage: 
-Similar to issue #56, hex color when fully zoomed out on the map. This will help showcase those areas which have more coverage (whereas the current zoomed-out map lacks these details). 

4. Preferred Language
- A dropdown menu for language, so all country and city names appear in the same preferred language of the user.

**Comment by jthiller** [comment]
Thanks Tim!

For the country and city names, I believe we'll need @PeterMain to poke at the mapbox styles.

---

Since we're on the topic of MapBox styles, I have two small changes I'd like to propose 
1. **Show bridges on vector layer.** Bridges don't seem to appear on the road layer. Would be good to get them back since it can lead to roads feeling like dead-ends. As shown below, the bridge doesn't appear to exist.
1.1 **Figure:** <img width="300" alt="image" src="https://user-images.githubusercontent.com/1965053/133855559-9bf2bce8-de99-40ea-a4c2-1ff4c2ca0507.png">

2. **Remove high-zoom overlay.** Minimizing the intensity or removing the dark overlay on high zoom levels would help in viewing trails, creeks, and other details that aren't represented on the vector layer. For example, when zooming in on the trail in the subsequent screenshot the color overlay obfuscates the image, making it difficult to view.
2.1 **Figure:** <img width="250" alt="image" src="https://user-images.githubusercontent.com/1965053/133857866-a94b0c89-94d1-46f3-87ef-d36f0a158f34.png">
2.2 **Figure:** <img width="250" alt="image" src="https://user-images.githubusercontent.com/1965053/133857883-fd9158d8-5ada-457c-ae08-1e00355fee53.png">

**Comment by PeterMain** [comment]
@jthiller Thanks for these. I've made some changes to the map style, so do let me know if that helps/any amendments are needed. Feel free to reopen issue.

**Comment by jthiller** [comment]
Thanks Pete. This seems to settle the main gist of this card. 
I'll make a new issue for i18n.
